name: Pre-production Pipeline

on:
  pull_request:
  pull_request_target:
  workflow_dispatch:

jobs:
  build:
    if: |
      (github.event_name == 'pull_request' && github.actor != 'dependabot[bot]') ||
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
      (github.event_name == 'workflow_dispatch')
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: List Files
        run: ls -al

      - name: Display content of application.txt
        run: cat application.txt

  build-container:
    name: Build Container
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get & Format Branch Name
        id: branch
        run: |
          name=${{ github.head_ref || github.ref_name }}
          name=${name//\//-}
          echo "name=$name" >> $GITHUB_OUTPUT

      - name: Display Branch Name
        run: echo ${{ steps.branch.outputs.name }}

      - name: Display SHA (Current commit)
        run: echo ${{ github.sha }}
