name: Production Pipeline

on:
  push:
    branches:
      - 'main'
  # Allows running the workflow manually via the actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get Previous Commit SHA
        run: echo "PREVIOUS_SHA=$(git rev-parse HEAD~1)" >> $GITHUB_ENV

      - name: Display SHA current commit
        run: echo ${{ github.sha }}

      - name: Display SHA previous commit (Latest commit of PR branch)
        run: echo ${{ env.PREVIOUS_SHA }}
